In [ ]:
import pandas as pd

In [ ]:
# 메서드 vs 함수 
# pandas -> Series 클래스-> isna() 메서드 -> 호출 방법 s.isna() 
# pandas -> concat() 함수 -> 호출 방법 pd.concat(s)

In [2]:
df= pd.DataFrame({
    "이름":["김민준","이서연","박지훈"],
    "점수":[80,90,75]
})

df

    이름  점수
0  김민준  80
1  이서연  90
2  박지훈  75

In [ ]:
a=df["점수"]
display(type(a))
display(a.dtype)
display(a.info())

pandas.Series

dtype('int64')

<class 'pandas.Series'>
RangeIndex: 3 entries, 0 to 2
Series name: 점수
Non-Null Count  Dtype
--------------  -----
3 non-null      int64
dtypes: int64(1)
memory usage: 156.0 bytes

None

In [14]:
b= df[["이름","점수"]]
display(type(b))
b

pandas.DataFrame

    이름  점수
0  김민준  80
1  이서연  90
2  박지훈  75

In [15]:
a=df[["점수"]]
display(type(a))

pandas.DataFrame

In [16]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    "직원ID": [101, 102, 103, 104, 105, 106, 107, 108],
    "이름": ["김민준", "이서연", "박지훈", "최유진",
           "정현우", "강수빈", "조민서", "윤도현"],
    "부서": ["개발", "영업", "개발", "인사",
           "영업", "개발", "영업", "인사"],
    "성별": ["남", "여", "남", "여", "남", "여", "여", "남"],
    "매출": [850, 920, np.nan, 780, 1200, 650, 920, np.nan],
    "근무시간": [160, 172, 168, 155, 180, 150, 172, 158],
    "등급": ["B", "A", "B", "C", "A", "C", "A", None],
    "입사년도": [2020, 2019, 2021, 2022, 2018, 2023, 2019, 2022]
})

display(df)

   직원ID   이름  부서 성별      매출  근무시간   등급  입사년도
0   101  김민준  개발  남   850.0   160    B  2020
1   102  이서연  영업  여   920.0   172    A  2019
2   103  박지훈  개발  남     NaN   168    B  2021
3   104  최유진  인사  여   780.0   155    C  2022
4   105  정현우  영업  남  1200.0   180    A  2018
5   106  강수빈  개발  여   650.0   150    C  2023
6   107  조민서  영업  여   920.0   172    A  2019
7   108  윤도현  인사  남     NaN   158  NaN  2022

In [ ]:
# 데이터 탐색
# head(데이터의 처음) -> tail(데이터의 끝) -> info(타입) -> describe(기술통계)

In [ ]:
# 통계(수치 데이터)  pandas) 기본적으로 null값을 제외하고 계산
df["매출"]

0     850.0
1     920.0
2       NaN
3     780.0
4    1200.0
5     650.0
6     920.0
7       NaN
Name: 매출, dtype: float64

In [ ]:
# 매출 갯수(null 제외)
df["매출"].count()

np.int64(6)

In [ ]:
# 매출평균
df["매출"].mean()

np.float64(886.6666666666666)

In [ ]:
# 표준편차
df["매출"].std()

np.float64(183.92027258208014)

In [ ]:
# 중앙값
df["매출"].median()

np.float64(885.0)

In [ ]:
# 사분위
df["매출"].quantile(0.75)

np.float64(920.0)

In [28]:
df["매출"].describe()

count       6.000000
mean      886.666667
std       183.920273
min       650.000000
25%       797.500000
50%       885.000000
75%       920.000000
max      1200.000000
Name: 매출, dtype: float64

In [21]:
#볌주형 데이터
df["성별"]

0    남
1    여
2    남
3    여
4    남
5    여
6    여
7    남
Name: 성별, dtype: str

In [23]:
# 종류 -> 빈도가 많은 값을 반환(동일해서 2개 반환)
df["성별"].mode()
df["부서"].mode()

0    개발
1    영업
Name: 부서, dtype: str

In [30]:
df["부서"].unique()

<StringArray>
['개발', '영업', '인사']
Length: 3, dtype: str

In [31]:
df["부서"].nunique()

3

In [ ]:
df["부서"].value_counts()

부서
개발    3
영업    3
인사    2
Name: count, dtype: int64

In [ ]:
# 결측치 확인 isna -> 결측지일 시 true 반환
df["매출"].isna()

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7     True
Name: 매출, dtype: bool

In [37]:
df["매출"].isnull()

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7     True
Name: 매출, dtype: bool

In [ ]:
# NaN(결측지) 대체: 대표값(평균,중앙값,최빈값)
# fillna

In [38]:
매출시리즈 = df["매출"]
매출시리즈

0     850.0
1     920.0
2       NaN
3     780.0
4    1200.0
5     650.0
6     920.0
7       NaN
Name: 매출, dtype: float64

In [ ]:
# NaN 값 평균으로 대체
매출시리즈 = df["매출"]
매출시리즈2= 매출시리즈.fillna(round(매출시리즈.mean()))
# 매출시리즈2= 매출시리즈.fillna(800)
매출시리즈2

0     850.0
1     920.0
2     887.0
3     780.0
4    1200.0
5     650.0
6     920.0
7     887.0
Name: 매출, dtype: float64

In [ ]:
# NaN 값 제거
매출시리즈3= 매출시리즈.dropna()
매출시리즈3

0     850.0
1     920.0
3     780.0
4    1200.0
5     650.0
6     920.0
Name: 매출, dtype: float64

In [ ]:
# 정렬  #ascending=True 오름차순 / ascending=False 내림차순
df["입사년도"].sort_values(ascending=True)

4    2018
1    2019
6    2019
0    2020
2    2021
3    2022
7    2022
5    2023
Name: 입사년도, dtype: int64

In [55]:
df["이름"].str  #str 속성을 시리즈 개별값으로 파이썬 문자열 메서드 사용가능
df["이름"].str.startswith("박")

0    False
1    False
2     True
3    False
4    False
5    False
6    False
7    False
Name: 이름, dtype: bool

In [ ]:
n1= pd.Series([" ab "," ab","ab ","a b"])
print(n1.str.strip())       # strip 공백 제거 / 중간공백은 X

0     ab
1     ab
2     ab
3    a b
dtype: str

In [ ]:
# describe() 입사년도 데이터 타입 변환 int->category(숫자 기술통계 X, 범주형 기술통계 O)
카테고리입사년도 = df["입사년도"].astype("category")
카테고리입사년도.describe()

count        8
unique       6
top       2019
freq         2
Name: 입사년도, dtype: int64

In [ ]:
nums = pd.Series(["1","2","3"])
n2= nums.astype(int)            #시리즈의 astype() 메서드   #NaN 있을 시 에러
n3= pd.to_numeric(nums)         #판다스의 to_numeric() 함수
#n3= pd.to_numeric(nums,errors="coerce") #에러는 NaN값으로 변환
display(n2)
display(n3)

0    1
1    2
2    3
dtype: int64

0    1
1    2
2    3
dtype: int64

In [63]:
#매출이 900 이상인 경우 조회
df["매출"].where(df["매출"]>900)

0       NaN
1     920.0
2       NaN
3       NaN
4    1200.0
5       NaN
6     920.0
7       NaN
Name: 매출, dtype: float64

In [ ]:
#매출이 900 이상인 것을 500으로 변환
df["매출"].mask(df["매출"]>900,500)

0    850.0
1    500.0
2      NaN
3    780.0
4    500.0
5    650.0
6    500.0
7      NaN
Name: 매출, dtype: float64

In [65]:
입사년도= df["입사년도"]
입사년도

0    2020
1    2019
2    2021
3    2022
4    2018
5    2023
6    2019
7    2022
Name: 입사년도, dtype: int64

In [66]:
# 중복 데이터 확인
입사년도.duplicated()

0    False
1    False
2    False
3    False
4    False
5    False
6     True
7     True
Name: 입사년도, dtype: bool

In [ ]:
# 중복 데이터 삭제
입사년도2 = 입사년도.drop_duplicates()
입사년도2

0    2020
1    2019
2    2021
3    2022
4    2018
5    2023
Name: 입사년도, dtype: int64

In [69]:
영어부서 = df["부서"]
영어부서

0    개발
1    영업
2    개발
3    인사
4    영업
5    개발
6    영업
7    인사
Name: 부서, dtype: str

In [70]:
영어부서2 =영어부서.replace({"개발":"Development"})
영어부서2

0    Development
1             영업
2    Development
3             인사
4             영업
5    Development
6             영업
7             인사
Name: 부서, dtype: str

In [ ]:
영어부서3= 영어부서.map({"개발":"Development","영업":"M","인사":"H"})
영어부서3

0    Development
1            NaN
2    Development
3            NaN
4            NaN
5    Development
6            NaN
7            NaN
Name: 부서, dtype: str

In [74]:
매출 = df["매출"]
매출

0     850.0
1     920.0
2       NaN
3     780.0
4    1200.0
5     650.0
6     920.0
7       NaN
Name: 매출, dtype: float64

In [76]:
# 구간별 값을 매핑하는 메서드 X
#apply(함수) 메서드: apply 메서드 매개값으로 들어갈 함수 선언(람다 사용가능)

def 매출_등급(val):
    if pd.isna(val): # val.isna() X, pd.isna(값) 함수 사용
        return "결측치"
    elif val >= 1000:
        return "상"
    elif val >= 800:
        return "중"
    else:
        return "하"

등급 = 매출.apply(매출_등급)
등급

0      중
1      중
2    결측치
3      하
4      상
5      하
6      중
7    결측치
Name: 매출, dtype: str

In [79]:
# 누적 통계기술량
df["매출"].cummax()
df["매출"].cumprod()

0    8.500000e+02
1    7.820000e+05
2             NaN
3    6.099600e+08
4    7.319520e+11
5    4.757688e+14
6    4.377073e+17
7             NaN
Name: 매출, dtype: float64

In [80]:
#시계열 데이터 값 이동 shift연산
df["매출"].shift(2)

0       NaN
1       NaN
2     850.0
3     920.0
4       NaN
5     780.0
6    1200.0
7     650.0
Name: 매출, dtype: float64

In [ ]:
# 값끼리의 차이
df["매출"].diff()

0      NaN
1     70.0
2      NaN
3      NaN
4    420.0
5   -550.0
6    270.0
7      NaN
Name: 매출, dtype: float64

In [82]:
df["매출"].pct_change()

0         NaN
1    0.082353
2         NaN
3         NaN
4    0.538462
5   -0.458333
6    0.415385
7         NaN
Name: 매출, dtype: float64

In [89]:
df["부서"].isin(["개발","인사"])

0     True
1    False
2     True
3     True
4    False
5     True
6    False
7     True
Name: 부서, dtype: bool

In [ ]:
#샘플 랜덤 선택(메서드)
df["이름"].sample(2, random_state=7)    # 7-> 특정 알고리즘 적용

2    박지훈
5    강수빈
Name: 이름, dtype: str

In [91]:
names= df["이름"]
display(type(names))
display(names)

pandas.Series

0    김민준
1    이서연
2    박지훈
3    최유진
4    정현우
5    강수빈
6    조민서
7    윤도현
Name: 이름, dtype: str

In [92]:
df_names= names.to_frame()
display(type(df_names))
df_names

pandas.DataFrame

    이름
0  김민준
1  이서연
2  박지훈
3  최유진
4  정현우
5  강수빈
6  조민서
7  윤도현

In [93]:
s1= pd.Series([1,2])
s2= pd.Series([1,2])
s3= s1.copy()
s4= s1

In [94]:
display(s2.equals(s1))
display(s3.equals(s1))
display(s4.equals(s1))

True

True

True

In [ ]:
s1[0]= 7
display(s2.equals(s1))  #False
display(s3.equals(s1))  #깊은복사+
display(s4.equals(s1))  #얕은복사

False

False

True