In [2]:
import pandas as pd

In [3]:
df1 = pd.DataFrame({
    "이름": ["홍길동", "김철수"],
    "점수": [80, 90]
})

df2 = pd.DataFrame({
    "이름": ["이영희", "박민수"],
    "점수": [85, 95]
})

display(df1)
display(df2)

    이름  점수
0  홍길동  80
1  김철수  90

    이름  점수
0  이영희  85
1  박민수  95

In [ ]:
# 데이터 합치기 concat
df = pd.concat([df1, df2], ignore_index=True, axis=0)
display(df)

    이름  점수
0  홍길동  80
1  김철수  90
2  이영희  85
3  박민수  95

In [7]:
df = pd.concat([df1, df2],ignore_index=False, axis=1)
display(df)

    이름  점수   이름  점수
0  홍길동  80  이영희  85
1  김철수  90  박민수  95

In [8]:
df1 = pd.DataFrame({
    "이름": ["김민수", "이서연"],
    "점수": [80, 90]
})

df2 = pd.DataFrame({
    "이름": ["박지훈", "최유진"],
    "등급": ["A", "B"]
})
display(df1)
display(df2)

    이름  점수
0  김민수  80
1  이서연  90

    이름 등급
0  박지훈  A
1  최유진  B

In [10]:
df=pd.concat([df1,df2])
df

    이름    점수   등급
0  김민수  80.0  NaN
1  이서연  90.0  NaN
0  박지훈   NaN    A
1  최유진   NaN    B

In [ ]:
df = pd.concat([df1, df2], join="outer", ignore_index=True) # join생략하면 기본값이 outer
display(df)

In [ ]:
# merge 함수: SQL JOIN 유사

df_customer = pd.DataFrame({
    "고객ID": [101, 102, 103, 104],
    "이름": ["홍길동", "김철수", "이영희", "박민수"]
})

df_score = pd.DataFrame({
    "고객ID": [101, 102, 103, 105],
    "점수": [90, 80, 95, 70]
})


display(df_customer)
display(df_score)

result = pd.merge(
    df_customer,
    df_score,
    on="고객ID",
    how="inner" # inner(기본값), left, right, outer
)

display(result)

   고객ID   이름
0   101  홍길동
1   102  김철수
2   103  이영희
3   104  박민수

   고객ID  점수
0   101  90
1   102  80
2   103  95
3   105  70

   고객ID   이름  점수
0   101  홍길동  90
1   102  김철수  80
2   103  이영희  95

In [13]:
result = pd.merge(
    df_score,
    df_customer,
    on="고객ID",
    how="left"
)

display(result)

   고객ID  점수   이름
0   101  90  홍길동
1   102  80  김철수
2   103  95  이영희
3   105  70  NaN