In [1]:
import pandas as pd

In [ ]:
df= pd.DataFrame({"이름":["김민준","이서연","박지훈"],"점수":["85","90","75"]},index= ["가","나","다"]) #index 매개값 생략시 Integer 위치값과 동일한 Index값을 기본값으로 생성
df

    이름  점수
가  김민준  85
나  이서연  90
다  박지훈  75

In [5]:
df.index.to_list()

['가', '나', '다']

In [7]:
df.index.name= "index"
df

        이름  점수
index
가      김민준  85
나      이서연  90
다      박지훈  75

In [8]:
df.index = [100,200,333]
df

      이름  점수
100  김민준  85
200  이서연  90
333  박지훈  75

In [12]:
#df의 인덱스 리셋

df2=df.reset_index()
df2

   index   이름  점수
0    100  김민준  85
1    200  이서연  90
2    333  박지훈  75

In [13]:
df.reset_index(inplace=True)
df

   index   이름  점수
0    100  김민준  85
1    200  이서연  90
2    333  박지훈  75

In [14]:
#열 -> 인덱스 set_index
df.set_index("index", inplace =True)
df

        이름  점수
index
100    김민준  85
200    이서연  90
333    박지훈  75