In [1]:
import pandas as pd

data = {
    "날짜": [
        "2025-01-01", "2025-01-02", "2025-01-03",
        "2025-02-01", "2025-02-02", "2025-02-03",
        "2025-03-01", "2025-03-02", "2025-03-03"
    ],
    "매출": [
        100, 120, None,
        200, None, 220,
        300, 320, None
    ]
}

df = pd.DataFrame(data)

df["날짜"] = pd.to_datetime(df["날짜"])

print(df)
print(df.info())

          날짜     매출
0 2025-01-01  100.0
1 2025-01-02  120.0
2 2025-01-03    NaN
3 2025-02-01  200.0
4 2025-02-02    NaN
5 2025-02-03  220.0
6 2025-03-01  300.0
7 2025-03-02  320.0
8 2025-03-03    NaN
<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   날짜      9 non-null      datetime64[us]
 1   매출      6 non-null      float64
dtypes: datetime64[us](1), float64(1)
memory usage: 276.0 bytes
None

In [2]:
df["월"] = df["날짜"].dt.month

df

          날짜     매출  월
0 2025-01-01  100.0  1
1 2025-01-02  120.0  1
2 2025-01-03    NaN  1
3 2025-02-01  200.0  2
4 2025-02-02    NaN  2
5 2025-02-03  220.0  2
6 2025-03-01  300.0  3
7 2025-03-02  320.0  3
8 2025-03-03    NaN  3

In [3]:
df.groupby("월").mean()

          날짜     매출
월
1 2025-01-02  110.0
2 2025-02-02  210.0
3 2025-03-02  310.0

In [4]:
cond= (df["월"] ==1)
cond

0     True
1     True
2     True
3    False
4    False
5    False
6    False
7    False
8    False
Name: 월, dtype: bool

In [5]:
df[cond]["매출"]                                #매출
df.loc[df["월"]==1, "매출"]                     #매출
#mean1= df.loc[df[cond]["매출"]].mean()          #평균
mean1= df.loc[df["월"]==1, "매출"].mean()       #평균
mean1

np.float64(110.0)

In [6]:
df.loc[df["월"]==2, "매출"]        
mean2= df.loc[df["월"]==2, "매출"].mean()
mean2
df.loc[df["월"]==3, "매출"]        
mean3= df.loc[df["월"]==3, "매출"].mean()
mean3

np.float64(310.0)

In [7]:
#결측지 전처리

cond=(df["매출"].isna()) & (df["월"]==1)        # 1월 중에 결측지 값 확인
df[cond]
df.loc[cond,"매출"] = mean1                    #1월 결측지 1월 평균값으로 채우기
cond=(df["매출"].isna()) & (df["월"]==2)        # 2월 중에 결측지 값 확인
df[cond]
df.loc[cond,"매출"] = mean2                    #2월 결측지 2월 평균값으로 채우기
cond=(df["매출"].isna()) & (df["월"]==3)        # 3월 중에 결측지 값 확인
df[cond]
df.loc[cond,"매출"] = mean3                    #3월 결측지 3월 평균값으로 채우기
df

          날짜     매출  월
0 2025-01-01  100.0  1
1 2025-01-02  120.0  1
2 2025-01-03  110.0  1
3 2025-02-01  200.0  2
4 2025-02-02  210.0  2
5 2025-02-03  220.0  2
6 2025-03-01  300.0  3
7 2025-03-02  320.0  3
8 2025-03-03  310.0  3

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
data = {
    "공부시간": [1, 2, 3, 4, 5, 6, 7, 8],
    "게임시간": [5, 4, 4, 3, 3, 2, 2, 1],
    "시험점수": [45, 50, None, 62, 68, None, 80, 88]
}

df = pd.DataFrame(data)

df

   공부시간  게임시간  시험점수
0     1     5  45.0
1     2     4  50.0
2     3     4   NaN
3     4     3  62.0
4     5     3  68.0
5     6     2   NaN
6     7     2  80.0
7     8     1  88.0

In [10]:
train = df[df["시험점수"].notna()]
train

   공부시간  게임시간  시험점수
0     1     5  45.0
1     2     4  50.0
3     4     3  62.0
4     5     3  68.0
6     7     2  80.0
7     8     1  88.0

In [18]:
x_train = train[["공부시간","게임시간"]]
y_train = train["시험점수"]
x_train
y_train

0    45.0
1    50.0
3    62.0
4    68.0
6    80.0
7    88.0
Name: 시험점수, dtype: float64

In [14]:
model = LinearRegression()
model.fit(x_train, y_train)
print(model.coef_)
print(model.intercept_)

[ 5.78571429 -0.60714286]
41.28571428571432

In [15]:
df[df["시험점수"].isna()]

   공부시간  게임시간  시험점수
2     3     4   NaN
5     6     2   NaN

In [ ]:
cond = df["시험점수"].isna()            #시험점수가 NaN 인 것
m=df.loc[cond,["공부시간","게임시간"]]

In [23]:
result_y=model.predict(m)
result_y

array([56.21428571, 74.78571429])

In [29]:
df.loc[cond, "시험점수"] = result_y.round(0)
df

   공부시간  게임시간  시험점수
0     1     5  45.0
1     2     4  50.0
2     3     4  56.0
3     4     3  62.0
4     5     3  68.0
5     6     2  75.0
6     7     2  80.0
7     8     1  88.0