In [1]:
import pandas as pd

df = pd.DataFrame({
    "부서": ["영업", "영업", "개발", "개발", "인사"],
    "이름": ["철수", "영희", "민수", "지수", "길동"],
    "매출": [100, 150, 200, 250, 120]
})

display(df)

   부서  이름   매출
0  영업  철수  100
1  영업  영희  150
2  개발  민수  200
3  개발  지수  250
4  인사  길동  120

In [3]:
print(df.groupby("부서")["매출"].mean())
print(df.groupby("부서")["매출"].sum())

부서
개발    225.0
영업    125.0
인사    120.0
Name: 매출, dtype: float64
부서
개발    450
영업    250
인사    120
Name: 매출, dtype: int64

In [6]:
print(df.groupby("부서")["매출"].describe())

    count   mean        std    min    25%    50%    75%    max
부서
개발    2.0  225.0  35.355339  200.0  212.5  225.0  237.5  250.0
영업    2.0  125.0  35.355339  100.0  112.5  125.0  137.5  150.0
인사    1.0  120.0        NaN  120.0  120.0  120.0  120.0  120.0

In [9]:
df.groupby("부서")["매출"].transform("mean")

0    125.0
1    125.0
2    225.0
3    225.0
4    120.0
Name: 매출, dtype: float64

In [11]:
df["부서별평균"] = df.groupby("부서")["매출"].transform("mean")
df

   부서  이름   매출  부서별평균
0  영업  철수  100  125.0
1  영업  영희  150  125.0
2  개발  민수  200  225.0
3  개발  지수  250  225.0
4  인사  길동  120  120.0

In [14]:
df2 = pd.DataFrame({
    "부서": ["영업", "영업", "개발", "개발", "인사"],
    "이름": ["철수", "영희", "민수", "지수", "길동"],
    "매출": [100, 150, 200, 250, 120]
})

df2

   부서  이름   매출
0  영업  철수  100
1  영업  영희  150
2  개발  민수  200
3  개발  지수  250
4  인사  길동  120

In [15]:
df_group=df2.groupby("부서")["매출"].mean()
df_group

부서
개발    225.0
영업    125.0
인사    120.0
Name: 매출, dtype: float64

In [20]:
df_group2=df_group.reset_index()
df_group3=df_group2.rename(columns={"매출":"평균"})
df_group3

   부서     평균
0  개발  225.0
1  영업  125.0
2  인사  120.0

In [21]:
df2.merge(df_group3,on="부서")

   부서  이름   매출     평균
0  영업  철수  100  125.0
1  영업  영희  150  125.0
2  개발  민수  200  225.0
3  개발  지수  250  225.0
4  인사  길동  120  120.0