In [ ]:
# 판다스 피벗   데이터의 행과 열변경
# 열 -> 행 melt / 행 -> 열 pivot(중복된 값이 있을 경우 pivot_table)
import pandas as pd

In [2]:
df = pd.DataFrame({
    "이름": ["철수", "영희"],
    "국어": [80, 90],
    "영어": [70, 95],
    "수학": [90, 85]
})

display(df)

   이름  국어  영어  수학
0  철수  80  70  90
1  영희  90  95  85

In [4]:
df_melt=df.melt(id_vars="이름", var_name="과목", value_name="점수")
df_melt

   이름  과목  점수
0  철수  국어  80
1  영희  국어  90
2  철수  영어  70
3  영희  영어  95
4  철수  수학  90
5  영희  수학  85

In [5]:
df_pivot= df_melt.pivot(index="이름",columns="과목",values="점수")
df_pivot

과목  국어  수학  영어
이름
영희  90  85  95
철수  80  90  70

In [6]:
result=df_pivot.reset_index()      # 인덱스값 초기화(기존 인덱스 컬럼으로 이동)
result

과목  이름  국어  수학  영어
0   영희  90  85  95
1   철수  80  90  70

In [ ]:
#pivot_table

df2 = pd.DataFrame({
    "이름": ["철수", "철수", "철수", "철수", "영희", "영희", "영희"],
    "과목": ["국어", "국어", "영어", "수학", "국어", "영어", "수학"],
    "점수": [80, 50, 70, 90, 90, 95, 85]
})

display(df2)

   이름  과목  점수
0  철수  국어  80
1  철수  국어  50
2  철수  영어  70
3  철수  수학  90
4  영희  국어  90
5  영희  영어  95
6  영희  수학  85

In [13]:
df3=df2.pivot_table(index="이름",columns="과목",values="점수", aggfunc="mean")
df3

과목    국어    수학    영어
이름
영희  90.0  85.0  95.0
철수  65.0  90.0  70.0

In [12]:
df3.reset_index()

과목  이름    국어    수학    영어
0   영희  90.0  85.0  95.0
1   철수  65.0  90.0  70.0