In [1]:
import seaborn as sns

In [3]:
mpg= sns.load_dataset("mpg")
mpg.info()

<class 'pandas.DataFrame'>
RangeIndex: 398 entries, 0 to 397
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           398 non-null    float64
 1   cylinders     398 non-null    int64
 2   displacement  398 non-null    float64
 3   horsepower    392 non-null    float64
 4   weight        398 non-null    int64
 5   acceleration  398 non-null    float64
 6   model_year    398 non-null    int64
 7   origin        398 non-null    str
 8   name          398 non-null    str
dtypes: float64(4), int64(3), str(2)
memory usage: 28.1 KB

In [4]:
mpg.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
1,15.0,8,350.0,165.0,3693,11.5,70,usa,buick skylark 320
2,18.0,8,318.0,150.0,3436,11.0,70,usa,plymouth satellite
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
4,17.0,8,302.0,140.0,3449,10.5,70,usa,ford torino

In [6]:
mpg["mpg"]

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [ ]:
t=[5,10,15,20]

[x>10 for x in t]

[x  for x in t if x>10]

[15, 20]

In [13]:
#문제 1. []로 열 선택
#mpg 데이터프레임에서 mpg 열만 선택하여 출력하시오.

mpg["mpg"]

0      18.0
1      15.0
2      18.0
3      16.0
4      17.0
       ...
393    27.0
394    44.0
395    32.0
396    28.0
397    31.0
Name: mpg, Length: 398, dtype: float64

In [21]:
#문제 2. []로 여러 열 선택
#mpg 데이터프레임에서 mpg, weight, origin 세 개의 열을 선택하여 출력하시오.

mpg[0:7:3]

,mpg,cylinders,displacement,horsepower,weight,acceleration,model_year,origin,name
0,18.0,8,307.0,130.0,3504,12.0,70,usa,chevrolet chevelle malibu
3,16.0,8,304.0,150.0,3433,12.0,70,usa,amc rebel sst
6,14.0,8,454.0,220.0,4354,9.0,70,usa,chevrolet impala

In [ ]:
#​문제 3. iloc로 특정 행 선택
#mpg에서 10번째 행의 데이터를 출력하시오.단, 숫자 위치를 이용하는 iloc을 사용하시오.
mpg.iloc[9]

mpg                           15.0
cylinders                        8
displacement                 390.0
horsepower                   190.0
weight                        3850
acceleration                   8.5
model_year                      70
origin                         usa
name            amc ambassador dpl
Name: 9, dtype: object

In [ ]:
#문제 4. iloc로 행 + 열 선택
#mpg에서 3번째 행의 1번째 열 값을 출력하시오.

mpg.iloc[2,0]

np.float64(18.0)

In [31]:
#문제 5. iloc로 행 + 열 슬라이싱
#mpg에서 1~5번째 행과 1~3번째 열을 선택하여 출력하시오.

mpg.iloc[0:5,0:3]

    mpg  cylinders  displacement
0  18.0          8         307.0
1  15.0          8         350.0
2  18.0          8         318.0
3  16.0          8         304.0
4  17.0          8         302.0

In [34]:
#문제 6. loc로 특정 행 + 열 선택
#mpg에서 인덱스가 10인 행의 mpg 값을 출력하시오.

mpg.loc[10,"mpg"]

np.float64(15.0)