In [2]:
import pandas as pd

df = pd.DataFrame({
    '이름': ['김철수', '이영희', '박민수', '최수진', '정우진'],
    '학년': [1, 2, 1, 3, 2],
    '점수': [85, 92, 78, 95, 88]
}, index=['A', 'B', 'C', 'D', 'E'])

print(df)
display(df)

    이름  학년  점수
A  김철수   1  85
B  이영희   2  92
C  박민수   1  78
D  최수진   3  95
E  정우진   2  88

    이름  학년  점수
A  김철수   1  85
B  이영희   2  92
C  박민수   1  78
D  최수진   3  95
E  정우진   2  88

In [39]:
df.loc["B","점수"]
df.iloc[1:2,0:3]
#df["이름"]  #열이름만 가능
#df["A":"B"]
#df["이름":"점수"]
#df["A":"A"]
df[["이름","학년"]]
df["A":"E"]
df[0:5]

    이름  학년  점수
A  김철수   1  85
B  이영희   2  92
C  박민수   1  78
D  최수진   3  95
E  정우진   2  88

In [ ]:
l= df["점수"]
df[l > 90]

df[df["점수"]>90]

    이름  학년  점수
B  이영희   2  92
D  최수진   3  95