In [ ]:
import pandas as pd

In [3]:
#{레이블:[], 레이블:[]}

df1 = pd.DataFrame({
    "이름":["민수","지영"],
    "점수":[90,85]
})

display(df1)

   이름  점수
0  민수  90
1  지영  85

In [6]:
df2= pd.DataFrame([
    ["민수",90],
    ["지영",85]
    ],index=["첫번째","두번째"],columns=["이름","점수"])

display(df2)

     이름  점수
첫번째  민수  90
두번째  지영  85

In [7]:
df3= pd.DataFrame([
    {"이름":"민수","점수":90},
    {"이름":"지영","점수":85}
])

display(df3)

   이름  점수
0  민수  90
1  지영  85

In [9]:
import numpy as np

df3 = pd.DataFrame(np.array([
    [1,2],
    [3,4]
]))

display(df3)

   0  1
0  1  2
1  3  4

In [18]:
df4 = pd.DataFrame({
    '이름': ['철수', '영희', '민수', '지영', '준호'],
    '나이': [20, 21, 20, 22, 21],
    '성별': ['남', '여', '남', '여', '남']
})

print(df4)

   이름  나이 성별
0  철수  20  남
1  영희  21  여
2  민수  20  남
3  지영  22  여
4  준호  21  남

In [16]:
df4.index
df4.columns
df4.values
df4.dtypes

이름      str
나이    int64
성별      str
dtype: object

In [ ]:
print(df4.shape,df4.size,df4.ndim)  #ndim -> 차원

(5, 3) 15 2

In [24]:
df4.info()
df4.head(2)

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   이름      5 non-null      str
 1   나이      5 non-null      int64
 2   성별      5 non-null      str
dtypes: int64(1), str(2)
memory usage: 252.0 bytes

   이름  나이 성별
0  철수  20  남
1  영희  21  여

In [ ]:
# 고유값 확인
df4["성별"].unique()    #SQL select distinct
# 고유값 갯수 확인
df4["성별"].nunique()

2